### ISSUE TITLE
关于15-一个调度相关的陷阱.md中内容的求证

### ISSUE THREAD

**Issue by lenuse** [golang-design/Go-Questions#35]
我在浏览其他博文的时候发现有提到go 1.14及之后的版本解决了这个问题。我在1.14的Release Notes中发现Goroutines 现在是异步可抢占的变为了异步抢占。

**Comment by changkun** [comment]
是的，这个问题已经解决了。可以在文中增加一个版本相关的提示。

**Comment by qcrao** [comment]
已注明
