### ISSUE TITLE
哈希表的遍历顺序是否有问题？

### ISSUE THREAD

**Issue by developerdong** [golang-design/go-questions#37]
[原文](https://golang.design/go-questions/map/range/)中提到
> 这样，遍历结果集变成：
> ![遍历结果](https://golang.design/go-questions/map/assets/11.png)

按照文中描述，从3号桶的2号cell开始往后顺序遍历。但我翻看了一下文中所使用的1.9.2的[源码](https://github.com/golang/go/blob/2ea7d3461bb41d0ae12b56ee52d43314bcdb97f9/src/runtime/hashmap.go#L820)以及最新的go1.17.5的[源码](https://github.com/golang/go/blob/de690c2ff8e323c7ce9e274f986dc6f824b35405/src/runtime/map.go#L899)，发现不管哪个Go版本，桶的遍历顺序是3->0->1->2，但每个桶内都要从offset处开始遍历，而不是前后首尾相接的遍历。所以最终的遍历顺序应该是**egfcbhda**，而不是**efgbchad**。

不知道我是否理解错误，欢迎讨论。

**Comment by qcrao** [comment]
对的。正式出版的书里已经更正过来了。谢谢指出，有兴趣可以提一个 pr~

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/7698088/168478722-92f51cb6-bb2b-4052-bd61-3754f0d22c4e.png">
