### ISSUE TITLE
Page 64 4-3 recv workflow graph

### ISSUE THREAD

**Issue by jiekun** [golang-design/go-questions#48]
## 实际描述

- 原文页码：64
- 原文段落：图 4-3

```
 缓冲区是否有数据？
- 是 ...
- 否 -> （返回true, true) -> 复制缓冲区元素
```

## 预期描述

```
 缓冲区是否有数据？
- 是 -> (返回true, true) -> 复制缓冲区元素
- 否 ...
```

所以如果没理解错的话，这好像是个比较大的错误了？

**Comment by tutulove1234** [comment]
我也发现了你说的这个问题，应该是图片把“是”和“否”写反了。

**Comment by tutulove1234** [comment]
作者已经在勘误列表中更新了：https://golang.design/go-questions/errata/#%e7%ac%ac-64-%e9%a1%b5
这个issue可以关闭了。
