### ISSUE TITLE
go-questions/content/channel/7-操作 channel 的情况总结.md    文章内容有误

### ISSUE THREAD

**Issue by wings132** [golang-design/go-questions#52]
## 实际描述

- 原文页码：go-questions/content/channel/7-操作 channel 的情况总结.md 
- 原文段落：

```
读、写一个 nil channel 都会被阻塞。
```

## 预期描述

```
读、写一个 nil channel 未初始化的channel都会导致deadlock。
```

## 附图

<img width="957" alt="WX20220716-174728@2x" src="https://user-images.githubusercontent.com/41111422/179349764-d4eac3e0-009b-4f77-9fa5-fcee9b8a78a5.png">

**Comment by And-ZJ** [comment]
我倒是觉得，读写 nil  channel，一定阻塞这点不是完全正确。例外就是 在 select 中，如果 select 可以选中其他case，并不会导致当前goroutine阻塞。如果没有case和default可以走，那么select会阻塞。

**Comment by qcrao** [comment]
> 我倒是觉得，读写 nil channel，一定阻塞这点不是完全正确。例外就是 在 select 中，如果 select 可以选中其他case，并不会导致当前goroutine阻塞。如果没有case和default可以走，那么select会阻塞。

你是对的。不过这是因为 channel 的读写流程里对 select 做了特殊的处理。
